var phoneDetail = [
    // Apple
    // List: iPhone 11, iPhone 11 Pro, iPhone 12, iPhone 12 Pro, iPhone 12 mini
    {
        "img": "./_img/Apple/Apple_iPhone_11.png",
        "brand": "Apple",
        "name": "iPhone 11",
        "os": "iOS 13",
        "processor": "Apple A13",
        "ram": "4",
        "rom": "128",
        "display": "6.1",
        "disp_tech": "Liquid Retina HD 顯示器",
        "refresh_rate": "60",
        "wide": "1200",
        "ois": ["主鏡頭"],
        "ultrawide": "1200",
        "telephoto": "none",
        "front_camera": "1200",
        "battery": "3110",
        "waterproof": "IP 68",
        "band_support": ["4G"],
        "charging_watt": "18",
        "weight": "194",
        "height": "150.9",
        "width": "75.7",
        "depth": "8.3",
        "price": "26900",
        "type": ["balance", "gaming"]
        
    },
    {
        "img": "./_img/Apple/Apple_iPhone_11_Pro.png",
        "brand": "Apple",
        "name": "iPhone 11 Pro",
        "os": "iOS 13",
        "processor": "Apple A13",
        "ram": "4",
        "rom": "256",
        "display": "5.8",
        "disp_tech": "超 Retina XDR 顯示器",
        "refresh_rate": "60",
        "wide": "1200",
        "ois": ["主鏡頭","望遠鏡頭"],
        "ultrawide": "1200",
        "telephoto": "1200",
        "front_camera": "1200",
        "battery": "3046",
        "waterproof": "IP 68",
        "band_support": ["4G"],
        "charging_watt": "18",
        "weight": "188",
        "height": "144.0",
        "width": "71.4",
        "depth": "8.1",
        "price": "41400",
        "type": ["flagship", "photography", "gaming"]
    },
    {
        "img": "./_img/Apple/Apple_iPhone_12.png",
        "brand": "Apple",
        "name": "iPhone 12",
        "os": "iOS 14",
        "processor": "Apple A14",
        "ram": "4",
        "rom": "128",
        "display": "6.1",
        "disp_tech": "超 Retina XDR 顯示器",
        "refresh_rate": "60",
        "wide": "1200",
        "ois": ["主鏡頭"],
        "ultrawide": "1200",
        "telephoto": "none",
        "front_camera": "1200",
        "battery": "2815",
        "waterproof": "IP 68",
        "band_support": ["4G","5G"],
        "charging_watt": "18",
        "weight": "162",
        "height": "146.7",
        "width": "71.5",
        "depth": "7.4",
        "price": "28500",
        "type": ["balance", "gaming"]
    },
    {
        "img": "./_img/Apple/Apple_iPhone_12_Pro.png",
        "brand": "Apple",
        "name": "iPhone 12 Pro",
        "os": "iOS 14",
        "processor": "Apple A14",
        "ram": "6",
        "rom": "128",
        "display": "6.1",
        "disp_tech": "超 Retina XDR 顯示器",
        "refresh_rate": "60",
        "wide": "1200",
        "ois": ["主鏡頭","望遠鏡頭"],
        "ultrawide": "1200",
        "telephoto": "1200",
        "front_camera": "1200",
        "battery": "2815",
        "waterproof": "IP 68",
        "band_support": ["4G","5G"],
        "charging_watt": "18",
        "weight": "187",
        "height": "146.7",
        "width": "71.5",
        "depth": "7.4",
        "price": "33900",
        "type": ["flagship", "photography", "gaming"]
    },
    {
        "img": "./_img/Apple/Apple_iPhone_12_mini.png",
        "brand": "Apple",
        "name": "iPhone 12 mini",
        "os": "iOS 14",
        "processor": "Apple A14",
        "ram": "4",
        "rom": "128",
        "display": "5.4",
        "disp_tech": "超 Retina XDR 顯示器",
        "refresh_rate": "60",
        "wide": "1200",
        "ois": ["主鏡頭"],
        "ultrawide": "1200",
        "telephoto": "none",
        "front_camera": "1200",
        "battery": "2227",
        "waterproof": "IP 68",
        "band_support": ["4G","5G"],
        "charging_watt": "18",
        "weight": "133",
        "height": "131.5",
        "width": "64.2",
        "depth": "7.4",
        "price": "25500",
        "type": ["mini"]
    },
    // ASUS
    {
        "img": "./_img/Asus/ROG_Phone_5.jpg",
        "brand": "ASUS",
        "name": "ROG Phone 5",
        "os": "Android 11",
        "processor": "Qualcomm Snapdragon 888",
        "ram": "16",
        "rom": "256",
        "display": "6.78 ",
        "disp_tech": "三星 AMOLED",
        "refresh_rate": "144",
        "wide": "6400",
        "ois": ["none"],
        "ultrawide": "1300",
        "telephoto": "none",
        "front_camera": "2400",
        "battery": "6000",
        "waterproof": "none",
        "band_support": ["4G","5G"],
        "charging_watt": "65",
        "weight": "238",
        "height": "172.8",
        "width": "77.2",
        "depth": "10.29",
        "price": "29990",
        "type": ["flagship","gaming"]
    },
    {
        "img": "./_img/Asus/ROG3.jpg",
        "brand": "ASUS",
        "name": "ROG Phone 3",
        "os": "Android 10",
        "processor": "Qualcomm Snapdragon 865 ",
        "ram": "12",
        "rom": "512",
        "display": "6.59",
        "disp_tech": "三星 AMOLED",
        "refresh_rate": "144",
        "wide": "6400",
        "ois": ["none"],
        "ultrawide": "1300",
        "telephoto": "none",
        "front_camera": "2400",
        "battery": "6000",
        "waterproof": "none",
        "band_support": ["4G","5G"],
        "charging_watt": "30",
        "weight": "240",
        "height": "171",
        "width": "171",
        "depth": "9.85",
        "price": "22399",
        "type": ["flagship","gaming"]
    },
    {
        "img": "./_img/Asus/ASUS_ZenFone_8.png",
        "brand": "ASUS",
        "name": "Zenfone 8",
        "os": "Android 11",
        "processor": "Snapdragon 888",
        "ram": "8",
        "rom": "128",
        "display": "5.9",
        "disp_tech": "OLED",
        "refresh_rate": "120",
        "wide": "6400",
        "ois": ["主鏡頭"],
        "ultrawide": "1200",
        "telephoto": "none",
        "front_camera": "1200",
        "battery": "4000",
        "waterproof": "IP 68",
        "band_support": ["4G","5G"],
        "charging_watt": "30",
        "weight": "169",
        "height": "148",
        "width": "68.5",
        "depth": "8.9",
        "price": "16500",
        "type": ["balance", "mini"]
    },
    {
        "img": "./_img/Asus/Zenfone8flip.png",
        "brand": "ASUS",
        "name": "Zenfone 8 flip",
        "os": "Android 11",
        "processor": "Snapdragon 888",
        "ram": "8",
        "rom": "128",
        "display": "6.67",
        "disp_tech": "OLED",
        "refresh_rate": "90",
        "wide": "6,400 ",
        "ois": ["none"],
        "ultrawide": "1200",
        "telephoto": "1200",
        "front_camera": "1200",
        "battery": "5000",
        "waterproof": "none",
        "band_support": ["4G","5G"],
        "charging_watt": "30",
        "weight": "230",
        "height": "165.04",
        "width": "77.28",
        "depth": "9.6",
        "price": "18500",
        "type": ["balance", "gaming"]
    },
    {
        "img": "./_img/Asus/ZenFone7.png",
        "brand": "ASUS",
        "name": "Zenfone 7",
        "os": "Android 10",
        "processor": "Snapdragon 865",
        "ram": "6",
        "rom": "128",
        "display": "6.67",
        "disp_tech": "OLED",
        "refresh_rate": "90",
        "wide": "6400 ",
        "ois": ["none"],
        "ultrawide": "1200",
        "telephoto": "800",
        "front_camera": "1200",
        "battery": "5000",
        "waterproof": "none",
        "band_support": ["4G","5G"],
        "charging_watt": "30",
        "weight": "230",
        "height": "165",
        "width": "77.28",
        "depth": "9.9",
        "price": "11700",
        "type": ["balance", "gaming"]
    },
    // Google
    {
        "img": "./_img/Google/Pixel 5 5G.jpg",
        "brand": "Google",
        "name": "Pixel 5",
        "os": "Android 11",
        "processor": "Qualcomm Snapdragon 765G",
        "ram": "8",
        "rom": "128",
        "display": "6",
        "disp_tech": "OLED",
        "refresh_rate": "90",
        "wide": "1200",
        "ois": ["主鏡頭"],
        "ultrawide": "1300",
        "telephoto": "none",
        "front_camera": "800",
        "battery": "4080",
        "waterproof": "IP 68",
        "band_support": ["4G","5G"],
        "charging_watt": "18",
        "weight": "151",
        "height": "144.7",
        "width": "70.4",
        "depth": "8",
        "price": "18200",
        "type": ["balance","photography","mini"]
    },
    {
        "img": "./_img/Google/Pixel 4a 5G.jpg",
        "brand": "Google",
        "name": "Pixel 4a 5G",
        "os": "Android 11",
        "processor": "Qualcomm Snapdragon 765G",
        "ram": "6",
        "rom": "128",
        "display": "6.2 ",
        "disp_tech": "OLED",
        "refresh_rate": "60",
        "wide": "1600",
        "ois": ["主鏡頭"],
        "ultrawide": "1300",
        "telephoto": "none",
        "front_camera": "800",
        "battery": "3885",
        "waterproof": "none",
        "band_support": ["4G","5G"],
        "charging_watt": "18",
        "weight": "168",
        "height": "153.9",
        "width": "74",
        "depth": "8.2",
        "price": "14500",
        "type": ["balance","photography"]
    },
    {
        "img": "./_img/Google/Pixel 4.jpg",
        "brand": "Google",
        "name": "Pixel 4",
        "os": "Android 10",
        "processor": "Qualcomm Snapdragon 855",
        "ram": "6",
        "rom": "128",
        "display": "5.81 ",
        "disp_tech": "OLED",
        "refresh_rate": "90",
        "wide": "1220",
        "ois": ["主鏡頭","望遠鏡頭"],
        "ultrawide": "none",
        "telephoto": "1600",
        "front_camera": "800",
        "battery": "2800",
        "waterproof": "IP 68",
        "band_support": ["4G"],
        "charging_watt": "18",
        "weight": "162",
        "height": "147.1",
        "width": "68.8",
        "depth": "8.2",
        "price": "24600",
        "type": ["flagship", "photography", "mini"]
    },
    {
        "img": "./_img/Google/3a.png",
        "brand": "Google",
        "name": "Pixel 3a",
        "os": "Android 9",
        "processor": "Snapdragon 670",
        "ram": "4",
        "rom": "64",
        "display": "5.6 ",
        "disp_tech": "OLED",
        "refresh_rate": "60",
        "wide": "1200",
        "ois": ["主鏡頭"],
        "ultrawide": "none",
        "telephoto": "none",
        "front_camera": "800",
        "battery": "3000",
        "waterproof": "none",
        "band_support": ["4G"],
        "charging_watt": "18",
        "weight": "147",
        "height": "151.3",
        "width": "70.1",
        "depth": "8.2",
        "price": "11,500",
        "type": ["communication"]
    },
    {
        "img": "./_img/Google/3.png",
        "brand": "Google",
        "name": "Pixel 3",
        "os": "Android 9",
        "processor": "Snapdragon 845",
        "ram": "4",
        "rom": "64",
        "display": "5.5",
        "disp_tech": "OLED",
        "refresh_rate": "60",
        "wide": "1220",
        "ois": ["主鏡頭"],
        "ultrawide": "none",
        "telephoto": "none",
        "front_camera": "800",
        "battery": "2915",
        "waterproof": "IP 68",
        "band_support": ["4G"],
        "charging_watt": "18",
        "weight": "148",
        "height": "145.6",
        "width": "68.2",
        "depth": "7.9",
        "price": "27700",
        "type": ["flagship", "mini"]
    },
    // HTC
    {
        "img": "./_img/Htc/U20 5G.jpg",
        "brand": "HTC",
        "name": "U20 5G",
        "os": "Android 10",
        "processor": "Qualcomm Snapdragon 765G",
        "ram": "8",
        "rom": "256",
        "display": "6.8 ",
        "disp_tech": "LCD",
        "refresh_rate": "60",
        "wide": "4800",
        "ois": ["主鏡頭"],
        "ultrawide": "800",
        "telephoto": "none",
        "front_camera": "3200",
        "battery": "5000",
        "waterproof": "none",
        "band_support": ["4G","5G"],
        "charging_watt": "18",
        "weight": "215.5",
        "height": "171.2",
        "width": "78.1",
        "depth": "9.4",
        "price": "18990",
        "type": ["balance"]
    },
    {
        "img": "./_img/Htc/Desire 21 pro 5G.jpg",
        "brand": "HTC",
        "name": "Desire 21 pro 5G",
        "os": "Android 10",
        "processor": "Qualcomm Snapdragon 690",
        "ram": "8",
        "rom": "128",
        "display": "6.7 ",
        "disp_tech": "LCD",
        "refresh_rate": "90",
        "wide": "4800",
        "ois": ["none"],
        "ultrawide": "800",
        "telephoto": "none",
        "front_camera": "1600",
        "battery": "5000",
        "waterproof": "none",
        "band_support": ["4G","5G"],
        "charging_watt": "18",
        "weight": "205",
        "height": "167.1",
        "width": "78.1",
        "depth": "9.4",
        "price": "11900",
        "type": ["communication"]

    },
    {
        "img": "./_img/Htc/Desire 20+.jpg",
        "brand": "HTC",
        "name": "Desire 20+",
        "os": "Android 10",
        "processor": "Qualcomm Snapdragon 720G",
        "ram": "6",
        "rom": "128",
        "display": "6.5 ",
        "disp_tech": "LCD",
        "refresh_rate": "60",
        "wide": "4800",
        "ois": ["none"],
        "ultrawide": "500",
        "telephoto": "none",
        "front_camera": "1600",
        "battery": "5000",
        "waterproof": "none",
        "band_support": ["4G"],
        "charging_watt": "18",
        "weight": "203",
        "height": "164.9",
        "width": "75.7",
        "depth": "9",
        "price": "8490",
        "type": ["balance"]
    },
    {
        "img": "./_img/Htc/Desire 20 pro.jpg",
        "brand": "HTC",
        "name": "Desire 20 Pro",
        "os": "Android 10",
        "processor": "Qualcomm Snapdragon 665",
        "ram": "6",
        "rom": "128",
        "display": "6.5 ",
        "disp_tech": "LCD",
        "refresh_rate": "60",
        "wide": "4800",
        "ois": ["none"],
        "ultrawide": "800",
        "telephoto": "none",
        "front_camera": "2500",
        "battery": "5000",
        "waterproof": "none",
        "band_support": ["4G"],
        "charging_watt": "18",
        "weight": "201",
        "height": "162",
        "width": "77",
        "depth": "9.4",
        "price": "8490",
        "type": ["communication"]
    },
    {
        "img": "./_img/Htc/HTC Desire 19s.png",
        "brand": "HTC",
        "name": "Desire 19s",
        "os": "Android 9",
        "processor": "Helio P22",
        "ram": "4",
        "rom": "64",
        "display": "6.2 ",
        "disp_tech": "LCD",
        "refresh_rate": "60",
        "wide": "1300",
        "ois": ["none"],
        "ultrawide": "800",
        "telephoto": "none",
        "front_camera": "1600",
        "battery": "3850",
        "waterproof": "none",
        "band_support": ["4G"],
        "charging_watt": "18",
        "weight": "170",
        "height": "156.2",
        "width": "74.8",
        "depth": "8.5",
        "price": "6990",
        "type": ["communication"]
    },
    // OPPO
    {
        "img": "./_img/Oppo/A54.png",
        "brand": "OPPO",
        "name": "A54",
        "os": "Android 10",
        "processor": "Helio P35",
        "ram": "4",
        "rom": "64",
        "display": "6.51",
        "disp_tech": "LCD",
        "refresh_rate": "120",
        "wide": "1300",
        "ois": ["none"],
        "ultrawide": "none",
        "telephoto": "none",
        "front_camera": "1,600",
        "battery": "5000",
        "waterproof": "IP X4",
        "band_support": ["4G"],
        "charging_watt": "18",
        "weight": "192",
        "height": "163.6",
        "width": "75.7",
        "depth": "8.4",
        "price": "4999",
        "type": ["communication"]
    },
    {
        "img": "./_img/Oppo/A74.png",
        "brand": "OPPO",
        "name": "A74",
        "os": "Android 11",
        "processor": "Snapdragon 480",
        "ram": "6",
        "rom": "128",
        "display": "6.5",
        "disp_tech": "LCD",
        "refresh_rate": "90",
        "wide": "4,800",
        "ois": ["none"],
        "ultrawide": "800",
        "telephoto": "none",
        "front_camera": "1600",
        "battery": "5000",
        "waterproof": "none",
        "band_support": ["4G","5G"],
        "charging_watt": "18",
        "weight": "194",
        "height": "162.9",
        "width": "74.7",
        "depth": "8.4",
        "price": "9990",
        "type": ["communication"]
    },
    {
        "img": "./_img/Oppo/FindX3Pro.png",
        "brand": "OPPO",
        "name": "Find X3 Pro",
        "os": "Android 11",
        "processor": "Snapdragon 888",
        "ram": "12",
        "rom": "256",
        "display": "6.7",
        "disp_tech": "十億色臻彩螢幕(OLED)",
        "refresh_rate": "120",
        "wide": "5000",
        "ois": ["主鏡頭"],
        "ultrawide": "5000",
        "telephoto": "1300",
        "front_camera": "3200",
        "battery": "4500",
        "waterproof": "IP 68",
        "band_support": ["4G","5G"],
        "charging_watt": "65",
        "weight": "193",
        "height": "163.6",
        "width": "74",
        "depth": "8.26",
        "price": "30900",
        "type": ["flagship","photography", "gaming"]
    },
    {
        "img": "./_img/Oppo/Reno5pro.png",
        "brand": "OPPO",
        "name": "Reno5 Pro",
        "os": "Android 11",
        "processor": "MediaTek Dimensity 1000+",
        "ram": "12",
        "rom": "256",
        "display": "6.55",
        "disp_tech": "OLED",
        "refresh_rate": "90",
        "wide": "6400",
        "ois": ["none"],
        "ultrawide": "800",
        "telephoto": "none",
        "front_camera": "3200",
        "battery": "4350",
        "waterproof": "none",
        "band_support": ["4G","5G"],
        "charging_watt": "65",
        "weight": "173",
        "height": "159.7",
        "width": "73.2",
        "depth": "7.6",
        "price": "15890",
        "type": ["gaming"]
    },
    {
        "img": "./_img/Oppo/Reno5z.png",
        "brand": "OPPO",
        "name": "Reno5 Z",
        "os": "Android 11",
        "processor": "MediaTek Dimensity 800U",
        "ram": "8",
        "rom": "128",
        "display": "6.43",
        "disp_tech": "OLED",
        "refresh_rate": "60",
        "wide": "4800",
        "ois": ["none"],
        "ultrawide": "800",
        "telephoto": "none",
        "front_camera": "1600",
        "battery": "4220",
        "waterproof": "none",
        "band_support": ["5G","5G"],
        "charging_watt": "30",
        "weight": "173",
        "height": "160.1",
        "width": "73.4",
        "depth": "7.8",
        "price": "10900",
        "type": ["balance"]
    },
    // Samsung
    {
        "img": "./_img/Sumsung/A22.jpg",
        "brand": "Samsung",
        "name": "Galaxy A22",
        "os": "Android 11",
        "processor": "MediaTek Dimensity 700",
        "ram": "4",
        "rom": "64",
        "display": "6.6",
        "disp_tech": "LCD",
        "refresh_rate": "90",
        "wide": "4800",
        "ois": ["none"],
        "ultrawide": "500",
        "telephoto": "none",
        "front_camera": "800",
        "battery": "5000",
        "waterproof": "none",
        "band_support": ["4G","5G"],
        "charging_watt": "15",
        "weight": "203",
        "height": "167.2",
        "width": "76.4",
        "depth": "9",
        "price": "6990",
        "type": ["communication"]
    },
    {
        "img": "./_img/Sumsung/Samsung_Galaxy_Note_20_Ultra.png",
        "brand": "Samsung",
        "name": "Note 20 Ultra",
        "os": "Android 10",
        "processor": "Snapdragon 865+",
        "ram": "12",
        "rom": "256",
        "display": "6.9",
        "disp_tech": "Dynamic AMOLED 2X",
        "refresh_rate": "120",
        "wide": "10800",
        "ois": ["主鏡頭", "望遠鏡頭"],
        "ultrawide": "1200 ",
        "telephoto": "1200",
        "front_camera": "1000",
        "battery": "4500",
        "waterproof": "IP 68",
        "band_support": ["4G","5G"],
        "charging_watt": "25",
        "weight": "208",
        "height": "164.8",
        "width": "77.2",
        "depth": "8.1",
        "price": "43900",
        "type": ["flagship", "photography", "gaming"]
    },
    {
        "img": "./_img/Sumsung/Samsung_Galaxy_A52_5G.png",
        "brand": "Samsung",
        "name": "Galaxy A52 5G",
        "os": "Android 11",
        "processor": "Snapdragon 750G",
        "ram": "6",
        "rom": "128",
        "display": "6.5",
        "disp_tech": "OLED",
        "refresh_rate": "120",
        "wide": "6400",
        "ois": ["主鏡頭"],
        "ultrawide": "1200 ",
        "telephoto": "none",
        "front_camera": "3200",
        "battery": "4500",
        "waterproof": "IP 67",
        "band_support": ["4G","5G"],
        "charging_watt": "25",
        "weight": "189",
        "height": "159.9",
        "width": "75.1",
        "depth": "8.4",
        "price": "10700",
        "type": ["balance"]
    },
    {
        "img": "./_img/Sumsung/Samsung_Galaxy_S21_Ultra.png",
        "brand": "Samsung",
        "name": "Galaxy S21 Ultra 5G",
        "os": "Android 11",
        "processor": "Snapdragon 888",
        "ram": "12",
        "rom": "256",
        "display": "6.8",
        "disp_tech": "Dynamic AMOLED 2X",
        "refresh_rate": "120",
        "wide": "10080",
        "ois": ["主鏡頭","望遠鏡頭"],
        "ultrawide": "1200",
        "telephoto": "1000",
        "front_camera": "4,000",
        "battery": "5,000",
        "waterproof": "IP 68",
        "band_support": ["4G","5G"],
        "charging_watt": "25",
        "weight": "227",
        "height": "165.1",
        "width": "75.6",
        "depth": "8.9",
        "price": "39900",
        "type": ["flagship", "photography", "gaming"]
    },
    {
        "img": "./_img/Sumsung/samsung-galaxy-z-fold2-5g.jpg",
        "brand": "Samsung",
        "name": "Galaxy Z Fold2",
        "os": "Android 10",
        "processor": "Snapdragon 865+",
        "ram": "12",
        "rom": "512",
        "display": "7.6",
        "disp_tech": "Dynamic AMOLED 2X",
        "refresh_rate": "120",
        "wide": "1200",
        "ois": ["主鏡頭","超廣角鏡頭","望遠鏡頭"],
        "ultrawide": "1200",
        "telephoto": "1200",
        "front_camera": "1000",
        "battery": "4500",
        "waterproof": "none",
        "band_support": ["5G", "4G"],
        "charging_watt": "25",
        "weight": "282",
        "height": "159.2 ",
        "width": "68",
        "depth": "16.8",
        "price": "71888",
        "type": ["flagship"]
    },
    // Sony
    {
        "img": "./_img/Sony/Sony_Xperia_1_III.png",
        "brand": "Sony",
        "name": "Xperia 1 III",
        "os": "Android 11",
        "processor": " Snapdragon 888",
        "ram": "12",
        "rom": "256",
        "display": "6.5",
        "disp_tech": "OLED",
        "refresh_rate": "120",
        "wide": "1,200",
        "ois": ["主鏡頭", "望遠鏡頭"],
        "ultrawide": "1200",
        "telephoto": "1200",
        "front_camera": "800",
        "battery": "4500",
        "waterproof": "IP 68",
        "band_support": ["4G","5G"],
        "charging_watt": "30",
        "weight": "187",
        "height": "165",
        "width": "71",
        "depth": "8.2",
        "price": "0",
        "type": ["flagship","photography","gaming"]
    },
    {
        "img": "./_img/Sony/1 ii.png",
        "brand": "Sony",
        "name": "Xperia 1 II",
        "os": "Android 10",
        "processor": "Snapdragon 865",
        "ram": "8",
        "rom": "256",
        "display": "6.5",
        "disp_tech": "OLED",
        "refresh_rate": "60",
        "wide": "1200",
        "ois": ["主鏡頭","望遠鏡頭"],
        "ultrawide": "1200",
        "telephoto": "1200",
        "front_camera": "800",
        "battery": "4000",
        "waterproof": "IP 65",
        "band_support": ["4G","5G"],
        "charging_watt": "18",
        "weight": "181",
        "height": "166",
        "width": "72",
        "depth": "7.9",
        "price": "35900",
        "type": ["flagship","photography","gaming"]
    },
    {
        "img": "./_img/Sony/5 ii.jpg",
        "brand": "Sony",
        "name": "Xperia 5 II",
        "os": "Android 10",
        "processor": "Snapdragon 865",
        "ram": "8",
        "rom": "256",
        "display": "6.1",
        "disp_tech": "OLED",
        "refresh_rate": "120",
        "wide": "1200",
        "ois": ["主鏡頭","望遠鏡頭"],
        "ultrawide": "1200",
        "telephoto": "1200",
        "front_camera": "800",
        "battery": "4000",
        "waterproof": "IP 65",
        "band_support": ["4G","5G"],
        "charging_watt": "21",
        "weight": "163",
        "height": "158",
        "width": "68",
        "depth": "8",
        "price": "29900",
        "type": ["balance","photography","gaming"]
    },
    {
        "img": "./_img/Sony/5 III.jpg",
        "brand": "Sony",
        "name": "Xperia 5 III",
        "os": "Android 11",
        "processor": "Snapdragon 888",
        "ram": "8",
        "rom": "256",
        "display": "6.1",
        "disp_tech": "OLED",
        "refresh_rate": "120",
        "wide": "1200",
        "ois": ["主鏡頭","望遠鏡頭"],
        "ultrawide": "1200",
        "telephoto": "1200",
        "front_camera": "800",
        "battery": "4500",
        "waterproof": "IP 68",
        "band_support": ["4G","5G"],
        "charging_watt": "30",
        "weight": "169",
        "height": "157",
        "width": "68",
        "depth": "8.2",
        "price": "0",
        "type": ["balance","photography","gaming"]
    },
    {
        "img": "./_img/Sony/10 III.jpg",
        "brand": "Sony",
        "name": "Xperia 10 III",
        "os": "Android 11",
        "processor": "Snapdragon 690",
        "ram": "6",
        "rom": "128",
        "display": "6",
        "disp_tech": "OLED",
        "refresh_rate": "60",
        "wide": "1200",
        "ois": ["主鏡頭"],
        "ultrawide": "800",
        "telephoto": "800",
        "front_camera": "800",
        "battery": "4500",
        "waterproof": "IP 68",
        "band_support": ["4G","5G"],
        "charging_watt": "18",
        "weight": "154",
        "height": "68",
        "width": "8.3",
        "depth": "169",
        "price": "12990",
        "type": ["balance"]
    }
]