var phones = [
    {
        "name" : "Sony Xperia 1 III",
        "processor" : "Qualcomm Snapdragon 888",
        "ram" : "12",
        "rom" : "256",
        "display" : "6.5",
        "mainCamera" : "1,200",
        "ultrawide" : "",
        "telephoto" : "",
        "frontCamera" : "800",
        "battery" : "4,500",
        "weight" : "187",
        "os" : "Android 11",
        "waterproof" : "IP68",
        "price" : "41,990",
        "height" : "",
        "width" : "",
        "depth" : ""
    },
    {
        "name" : "ASUS ZenFone 8",
        "processor" : "Qualcomm Snapdragon 888",
        "ram" : "8",
        "rom" : "128",
        "display" : "5.9",
        "mainCamera" : "6,400",
        "ultrawide" : "",
        "telephoto" : "",
        "frontCamera" : "1,200",
        "battery" : "4,000",
        "weight" : "169",
        "os" : "Android 11",
        "waterproof" : "IP68",
        "price" : "18,900",
        "height" : "",
        "width" : "",
        "depth" : ""
    },
    {
        "name" : "iPhone 12 Pro",
        "processor" : "Apple A14",
        "ram" : "6",
        "rom" : "256",
        "display" : "6.1",
        "mainCamera" : "1,200",
        "ultrawide" : "",
        "telephoto" : "",
        "frontCamera" : "1,200",
        "battery" : "2,815",
        "weight" : "189",
        "os" : "iOS 14",
        "waterproof" : "IP68",
        "price" : "37,400",
        "height" : "",
        "width" : "",
        "depth" : ""
    },
    {
        "name" : "Samsung Galaxy S21 Ultra",
        "processor" : "Qualcomm Snapdragon 888",
        "ram" : "16",
        "rom" : "512",
        "display" : "6.8",
        "mainCamera" : "10,800",
        "ultrawide" : "",
        "telephoto" : "",
        "frontCamera" : "4,000",
        "battery" : "5,000",
        "weight" : "229",
        "os" : "Android 11",
        "waterproof" : "IP68",
        "price" : "43,900",
        "height" : "",
        "width" : "",
        "depth" : ""
    },
    {
        "name" : "Xiaomi Mi 11",
        "processor" : "Qualcomm Snapdragon 888",
        "ram" : "8",
        "rom" : "256",
        "display" : "6.81",
        "mainCamera" : "10,800",
        "ultrawide" : "",
        "telephoto" : "",
        "frontCamera" : "2,000",
        "battery" : "4,600",
        "weight" : "196",
        "os" : "Android 11",
        "waterproof" : "IP68",
        "price" : "21,999",
        "height" : "",
        "width" : "",
        "depth" : ""
    },
    {
        "name" : "Samsung Galaxy A52 5G",
        "processor" : "Qualcomm Snapdragon 750G",
        "ram" : "8",
        "rom" : "256",
        "display" : "6.5",
        "mainCamera" : "6,400",
        "ultrawide" : "",
        "telephoto" : "",
        "frontCamera" : "3,200",
        "battery" : "4,500",
        "weight" : "189",
        "os" : "Android 11",
        "waterproof" : "IP67",
        "price" : "15,900",
        "height" : "",
        "width" : "",
        "depth" : ""
    }
];